config/routes.rb
Rails.application.routes.draw do
  resources :locks
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'link/(:code)', to: 'locks#link', as: 'link'
  get 'welcome', to: 'sessions#new', as: 'welcome'
  # get 'auth/:provider/callback', to: 'sessions#create'
  get 'login', to: 'sessions#create',  as: :create_login
  get 'auth/failure', to: redirect('/')

  get 'auth/failure', to: redirect('/')
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root "sessions#redirecting"

end

app/models/lock.rb
class Lock < ApplicationRecord
  belongs_to :user
	before_save :check_code 

  def check_code
		puts "check code"
		self.code = [*('a'..'z'),*('0'..'9')].shuffle[0,8].join unless self.code
	end


	def generate_code
		[*('a'..'z'),*('0'..'9')].shuffle[0,8].join
	end

end

app/controllers/locks_controller.rb
class LocksController < ApplicationController
  before_action :set_lock, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user,  :except => [:show, :link]
  skip_before_action :verify_authenticity_token, only: :link

  # GET /locks
  # GET /locks.json
  def index
    # @locks = Lock.all
    @locks =  policy_scope(Lock)
  end

  # GET /locks/1
  # GET /locks/1.json
  def show
    authorize @lock
  end

  # GET /locks/new
  def new
    authorize Lock
    @lock = Lock.new
  end

  # GET /locks/1/edit
  def edit
    authorize @lock
  end

  # POST /locks
  # POST /locks.json
  def create
    authorize Lock
    @lock = Lock.new(lock_params)

    respond_to do |format|
      if @lock.save
        format.html { redirect_to @lock, notice: 'Lock was successfully created.' }
        format.json { render :show, status: :created, location: @lock }
      else
        format.html { render :new }
        format.json { render json: @lock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locks/1
  # PATCH/PUT /locks/1.json
  def update
    respond_to do |format|
      if @lock.update(lock_params)
        format.html { redirect_to @lock, notice: 'Lock was successfully updated.' }
        format.json { render :show, status: :ok, location: @lock }
      else
        format.html { render :edit }
        format.json { render json: @lock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locks/1
  # DELETE /locks/1.json
  def destroy
    @lock.destroy
    respond_to do |format|
      format.html { redirect_to locks_url, notice: 'Lock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def link
    @lock = Lock.find_by_code(params['code'].downcase) if params['code']
    if @lock != nil
      respond_to do |format|
          format.html {  }
          format.json { render json: @lock.as_json(only: [:url]) }
          format.js do
            render :json => @lock.as_json(only: [:url]), :callback => params[:callback]
            puts "jsonp"
          end
      end
    else
      respond_to do |format|
        format.html {  }
        format.json { render json: {"url" => "/link"}.as_json }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lock
      @lock = Lock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lock_params
      params.require(:lock).permit(:url, :user_id, :name)
    end
end

app/helpers/locks_helper.rb
module LocksHelper
end

app/views/locks/_form.html.slim
= simple_form_for(@lock) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :url
    = f.input_field :user_id, :as => "hidden",  :value => (@lock.user ? @lock.user.id : current_user.id ) 



  .form-actions
    = f.button :submit, class: "btb btn-primary"

app/views/locks/_redirect_form.html.slim
.form-group.text-center

  .control-label
    = label_tag "code", "Test Code: "

  .form-control
    = text_field_tag "code"

.form-group.text-center
    = button_tag "submit", id: "element", class: "btn btn-primary element"

app/views/locks/edit.html.slim
h3 Editing lock

== render 'form'


div.text-center
  = link_to 'Show', @lock, class: "btn btn-default"
  '&nbsp;
  = link_to 'Back', locks_path, class: "btn btn-default"


legend
  'Show URL

div.row.row-eq-height
  lable.col-lg-2.text-right
    strong Name:
  p.col-lg-10
    = @lock.name ? @lock.name : "-"

div.row.row-eq-height
  lable.col-lg-2.text-right
    strong Url:
  p.col-lg-10
    a href=@lock.url
      = @lock.url
      = ' - ' unless @lock.url


div.row.row-eq-height
  lable.col-lg-2.text-right
    strong Code:
  p.col-lg-10
    = @lock.code ? @lock.code : "-"
    |   -   
    = link_to "Reset", lock_path(id: @lock.id, "lock[code]" => 'reset'), :method => :patch

div.row.row-eq-height
  lable.col-lg-2.text-right
    strong User:
  p.col-lg-10
    = link_to @lock.user.username, user_path(@lock.user)

div.col-lg-10.col-lg-offset-2
  = link_to 'Edit', edit_lock_path(@lock), class: "btn btn-default"
  |&nbsp;
  = link_to 'Back', locks_path, class: "btn btn-default"

app/views/locks/index.html.slim
h3 Locks

table.table
  thead
    tr
      th Name
      th.hidden-xs
        | Url
      th.hidden-xs
        | User
      th

  tbody
    - @locks.each do |lock|
      tr
        td
          = lock.name
          <br/>
          = link_to(lock.url,lock.url, class: "visible-xs-inline")
        td.hidden-xs
          = link_to(lock.url,lock.url)
        td.hidden-xs
          = link_to lock.user.username, user_path(lock.user) if lock.user
        td.text-center
           = link_to 'Show', lock
           | &nbsp;|&nbsp;
           = link_to 'Edit', edit_lock_path(lock)
           | &nbsp;|&nbsp;
           = link_to 'Destroy', lock, data: { confirm: 'Are you sure?' }, method: :delete

br

.text-center
  = link_to 'New Lock', new_lock_path, class: "btn btn-default"

app/views/locks/link.html.slim
== render 'redirect_form'

app/views/locks/new.html.slim
h3 New lock

== render 'form'

.text-center
  = link_to 'Back', locks_path, class: "btn btn-default"

app/views/locks/show.html.slim
.container.vertical-center
	
	= link_to(locks_path(), class: "btn btn-default google-login google-login-md hidden-md hidden-lg") do
		= @lock.code
	= link_to(locks_path(), class: "btn btn-default google-login google-login-lg hidden-xs hidden-sm ") do
		= @lock.code